title: "@Virenbar"
url: "https://virenbar.net"
baseurl: ""
description: "The personal website of Virenbar, a .NET and TS developer living and working in Ural, Yekaterinburg."

plugins:
  - jekyll-sitemap

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      lang: ru

  - scope:
      path: "en"
    values:
      lang: en
      langurl: "/en"

  - scope:
      path: "es"
    values:
      lang: es
      langurl: "/es"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:categories/:year/:month/:day/:title
