plugins:
  - jekyll-sitemap

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"

collections:
  authors:
    output: true
  programs:
    output: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "_programs"
      type: "programs"
    values:
      layout: "program"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
  - scope:
      path: ""
    values:
      layout: "single"

permalink: /:categories/:title/