title: "@Virenbar"
baseurl: "/"
url: "https://virenbar.net"

plugins:
  - jekyll-sitemap

collections:
  projects:
    output: true

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:categories/:year/:month/:day/:title
